### ISSUE TITLE
Plugin system - progress tracker

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#103]
**Motivation**

Since the plugin system comprises several moving parts and many actions need to be performed in the correct order, I created this issue to keep track of their progress. So, what better place than the evolution repository for that? :smile_cat: 

**Overview**

Briefly, before releasing the plugin system feature, the following must be completed and incorporated into our GitHub organization:

- the [Plugin System proposal](https://github.com/falcosecurity/falco/blob/master/proposals/20210501-plugin-system.md), _already accepted_
- the [Plugin System support](https://github.com/falcosecurity/libs/pull/33) in `libscap` and `lipsinsp`, _in progress_ 
- the Plugin System feature in Falco (that depends on the previous point), _in progress_
- the [Golang SDK](https://github.com/falcosecurity/evolution/issues/101) to ease the writing of plugins in Golang, as foreseen by the proposal, _inital draft ready_
- the [Plugin repository](https://github.com/falcosecurity/evolution/issues/62) where concrete plugin implementations will live
- the official [Plugin Documentation](https://github.com/falcosecurity/falco-website/pull/493) to be included in the Falco's website, _draft ready_

**TODO list**

Some tasks are needed to get the desidered results. Moreover, some of them depend on others that need to be worked on before. So, here is the full task list in the expected order:

- [x] Proposal accepted
- [x] Add plugin support to https://github.com/falcosecurity/libs, all relevant PRs need to get merged in (WIP here :point_right: https://github.com/falcosecurity/libs/tree/new/plugin-system-api-additions, TBD list PRs here)
- [x] Move https://github.com/mstemm/plugin-sdk-go/ to the Falcosecurity org
    - ~[ ] (maybe) Add correct circleci secret to circleci webhook~ (We'll use prow for builds instead)
    - ~[ ] (maybe) Add a circleci deploy key~ (We'll use prow for builds instead)
- [x] Create an OWNER file for the `plugin-sdk-go` repository
- [x] Configure the repo and set up the Prow (@poiana) workflow (PR https://github.com/falcosecurity/test-infra/pull/515)
- [x] Document that the `plugin-sdk-go` repository has been adopted as an incubating project (PR https://github.com/falcosecurity/evolution/pull/104)
- [x] Make sure plugin-sdk-go go docs are available at pkg.go.dev
- [x] Add plugin support to https://github.com/falcosecurity/falco, all relevant PRs need to get merged in (TBD, list PRs here)
- [x] Move https://github.com/mstemm/plugins to the Falcosecurity org
    - ~[ ] (maybe) Add correct circleci secret to circleci webhook~ (We'll use prow for builds instead)
    - ~[ ] (maybe) Add a circleci deploy key~ (We'll use prow for builds instead)
- [x] Create an OWNER file for the `plugins` repository
- [x] Configure the repo and set up the Prow (@poiana) workflow (PR https://github.com/falcosecurity/test-infra/pull/516)
- [x] Document that the `plugins` repository has been adopted as an incubating project (~~maybe we want to promote this repo as "official" directly?~~) (PR https://github.com/falcosecurity/evolution/pull/105)
- [ ] Make the first release of `plugin-sdk-go` with the version equals to 0.1.0 (DO NOT do that until we assume the APIs are stable enough)
- [ ] (maybe) Make the first release of all (or some) plugins included in the registry
- [ ] Release a Falco version that includes the plugin's support (the plugin system will become official from this point on)
- [ ] Add the plugin documentation to https://github.com/falcosecurity/falco-website (WIP here :point_right: https://github.com/falcosecurity/falco-website/pull/493)

/assign @leogr
/assign @mstemm

**Comment by leogr** [comment]
Hey @mstemm 

I have added some suggestions to your test-infra PRs. Also, I have made two PR to add a notice in both projects' README to reflect their current status. 
PTAL :pray:

**Comment by leogr** [comment]
I believe that everything is ok now :smiley: 

so 
/close
