### ISSUE TITLE
[tracking] Preparation for Falco Graduation

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#156]
**Motivation**

We recently discussed the future of Falco, and we think it is in good shape and ready to try for CNCF graduation again. However, before submitting the graduation proposal again, some preparation is required. This issue aims to track the progress of this process.

**Refs**
 - relevant community calls: 2022-06-29, 2022-07-06
 - [previous security audit](https://github.com/falcosecurity/falco/blob/master/audits/SECURITY_AUDIT_2019_07.pdf)
 - previous [graduation proposal](https://github.com/cncf/toc/pull/641) (on Apr 2021)

**Action items**
Status: *work in progress*

We will add action items as they come and constantly update this issue with their progress.

- [x] Review of the maintainer list
  - [x] https://github.com/falcosecurity/evolution/issues/157 
- [x] Getting in touch with Tag Security leads
  - [x] Email sent
  - Response: A new audit is recommended
- [x] Requesting a new security audit (via CNCF service desk)
  - Getting in touch with the company that will perform the security audit
- [x] Reviewing inactive projects 
- [x] Kicking off a new security audit
- [x] Update the governance document :point_right: https://github.com/falcosecurity/evolution/pull/169
- [x] Ensure community docs are up-to-date and consistent :point_right: https://github.com/falcosecurity/evolution/issues/171
- [x] Sync core maintainers list to [maintainers.cncf.io](https://maintainers.cncf.io/) and `cncf-falco-maintainers@lists.cncf.io` :point_right: https://github.com/cncf/foundation/pull/410

**Comment by leogr** [comment]
Quick Update:
After recent discussions, maintainers agree we need to improve our governance to be less ambiguous and clarify roles within the project. We will first work on a draft, and get advice from CNCF's TAG Contributor Strategy's Governance working group. Anyone from willing to be involved in this activity is welcome.

**Comment by leogr** [comment]
Update: 
All core maintainers are now members of `cncf-falco-maintainers@lists.cncf.io` :partying_face:

**Comment by leogr** [comment]
See https://github.com/cncf/toc/pull/956 :partying_face: 
/close
