### ISSUE TITLE
[tracking] cleanup inactive maintainers

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/evolution#157]
### Motivation

As part of the preparations for our graduation submission, this issue tracks the process of reviewing and cleaning up the OWNERS files of each repository. This is a step for https://github.com/falcosecurity/falco/issues/2106 and follows the community call discussion of 2022-06-29.

The OWNERS files of each repository will be updated to remove maintainers that have been inactive for the past 6 months as for the criteria of our governance (see: https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#project-inactivity).

Developer activity is reviewed from the https://devstats.cncf.io/ API (ref: https://github.com/cncf/devstatscode/blob/master/API.md, https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt.sh). Inactivity means having recorded zero or very little devstats over the past 6 months (2022-01-01 - 2022-07-01).

Inactive maintainers will be moved from `approvers` to `emeritus_approvers` (see: https://www.kubernetes.dev/docs/guide/owners/#emeritus) so that they will have the possibility to step up again in the future.

If any of the maintainers involved wishes to continue with their role, or to become active again, this issue (or any of its linked PRs) is the right place of discussion.

These repositories are excluded from the rewiew:

  - ~**Special repositories**~ (see: https://github.com/falcosecurity/evolution/issues/157#issuecomment-1187476606)
    - ~falcosecurity/community~
    - ~falcosecurity/evolution~
    - ~falcosecurity/.github~
    - ~falcosecurity/template-repository~ (see: https://github.com/falcosecurity/evolution/issues/154)
  - **Repositories opened less than 6 months ago**
    - falcosecurity/deploy-kubernetes
    - falcosecurity/kernel-crawler
    - falcosecurity/plugin-sdk-cpp
    - falcosecurity/falco-aws-terraform
    - falcosecurity/libs-sdk-go
  - **Repositories that had no activity (or very little) in the past 6 months**
    - falcosecurity/katacoda-scenarios
    - falcosecurity/client-py
    - falcosecurity/client-rs
    - falcosecurity/kilt
    - falcosecurity/pdig

### Repositories where inactive owners need to be updated

- [x] falcosecurity/falco - ~https://github.com/falcosecurity/falco/pull/2116~, https://github.com/falcosecurity/falco/pull/2134
- [x] falcosecurity/libs - ~https://github.com/falcosecurity/libs/pull/460~, https://github.com/falcosecurity/libs/pull/489
- [x] falcosecurity/charts - ~https://github.com/falcosecurity/charts/pull/360~, https://github.com/falcosecurity/charts/pull/368, https://github.com/falcosecurity/charts/pull/369
- [x] falcosecurity/falco-website - ~https://github.com/falcosecurity/falco-website/pull/642~, https://github.com/falcosecurity/falco-website/pull/655
- [x] falcosecurity/plugins - ~https://github.com/falcosecurity/plugins/pull/129~, https://github.com/falcosecurity/plugins/pull/133
- [x] falcosecurity/plugin-sdk-go - ~https://github.com/falcosecurity/plugin-sdk-go/pull/58~, https://github.com/falcosecurity/plugin-sdk-go/pull/64
- [x] falcosecurity/client-go - ~https://github.com/falcosecurity/client-go/pull/57~, https://github.com/falcosecurity/client-go/pull/59
- [x] falcosecurity/driverkit - ~https://github.com/falcosecurity/driverkit/pull/179~, https://github.com/falcosecurity/driverkit/pull/188
- [x] falcosecurity/event-generator - ~https://github.com/falcosecurity/event-generator/pull/73~, https://github.com/falcosecurity/event-generator/pull/76
- [x] falcosecurity/falco-exporter - https://github.com/falcosecurity/falco-exporter/pull/73
- [x] falcosecurity/falcoctl - ~https://github.com/falcosecurity/falcoctl/pull/111~, https://github.com/falcosecurity/falcoctl/pull/113
- [x] falcosecurity/falcosidekick - https://github.com/falcosecurity/falcosidekick/pull/342, https://github.com/falcosecurity/falcosidekick/pull/343
- [x] falcosecurity/falcosidekick-ui - https://github.com/falcosecurity/falcosidekick-ui/pull/56, https://github.com/falcosecurity/falcosidekick-ui/pull/57
- [x] falcosecurity/test-infra - ~https://github.com/falcosecurity/test-infra/pull/751~, https://github.com/falcosecurity/test-infra/pull/768
- [x] falcosecurity/evolution - https://github.com/falcosecurity/evolution/pull/155
- [x] falcosecurity/community - https://github.com/falcosecurity/community/pull/151
- [x] falcosecurity/.github - https://github.com/falcosecurity/.github/pull/84

**Comment by jasondellaluce** [comment]
Closing this issue as the checklist is now complete.

/close
