### ISSUE TITLE
[tracking] Governance update follow-up

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#171]
**Motivation**

This issue is a task list of actions to be performed after #169 gets merged.
The motivation to perform some actions after is because #169 is already too big, and some tasks may require PRs in other repositories.

**TODOs**

- [x] Remove the old [falcosecurity/.github/blob/master/GOVERNANCE.md](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md)
- [x] Remove the old [falcosecurity/.github/blob/master/CODE_OF_CONDUCT.md](https://github.com/falcosecurity/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] ~~Move [falcosecurity/.github/blob/master/CONTRIBUTING.md](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md) to the `falcosecurity/evolution` and update it accordingly to the new governance document~~ We decided to keep it there, since it's required by GitHub as a health file
- [x] Move [falcosecurity/.github/blob/master/maintainers.yaml](https://github.com/falcosecurity/.github/blob/master/maintainers.yaml) to the `falcosecurity/evolution` and update the automation
- [x] Create a new `core-maintainers.yaml` file under the `falcosecurity/evolution` and create a Falco infra job to update it automatically
- [x] TBD: do we want the maintainers' lists rendered in Markdown?
- [x] Update all relevant links across the organization
- [x] Create a TOC/header for all documents that include links to other documents so that contributors can reach all docs from one place. See https://github.com/falcosecurity/evolution/pull/169#issuecomment-1210896761
- [x] Update [falcosecurity/evolution/blob/master/README.md](https://github.com/falcosecurity/evolution/blob/master/README.md) to reflect the status of the new governance and other documents.

Notes:
For documents to be moved or removed, we will not actually remove them from the origin place. We will instead create an almost empty file that redirects contributors to the new document.

**Comment by leogr** [comment]
Hoping that I haven't forgotten anything, it should all be set :smile_cat: 

/close
