### ISSUE TITLE
[tracking] moving rules out from the `falcosecurity/falco` repository

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#229]
**Motivation**

See https://github.com/falcosecurity/falco/blob/master/proposals/20221129-artifacts-distribution.md#move-falco-rules-to-their-own-repo

Since the final goal involves multiple repos, I've opened an issue here to track the progress:

**TODOs**

- [x] Extract the rules/ folder preserving the git history
- [x] Create a rules repository (TBD the name)
- [x] CI (in progress)
- [x] remove the rules/ folder from the falco repo

**Alternatives**

**Additional context**

**Comment by maxgio92** [comment]
Thank you @leogr for this and the well written and detailed proposal.

**Comment by LucaGuerra** [comment]
Thanks Leonardo, I agree having rules outside of the main Falco repo (and release schedule) will definitely be beneficial!

I believe you may need Falco core maintainers to help you with approves and reviews, I would like to volunteer for this as a repo maintainer if you agree. In addition I think that current active rules reviewer should continue to contribute as reviewers there, that would be @darryk10 in my opinion. WDYT?

**Comment by loresuso** [comment]
Thank you Leonardo for this proposal! 
+1 from my side for @LucaGuerra maintainership and moving @darryk10 as a reviewer here to continue his incredible work.

I want to propose myself as a reviewer as well. In the past, I have contributed to new rules, implemented new fields to write more powerful ones, and reviewed some of them, and since I am interested in security I'd like to help and join the effort.

Let me know what you think!

**Comment by LucaGuerra** [comment]
> I want to propose myself as a reviewer as well.

+1

**Comment by leogr** [comment]
@LucaGuerra and @loresuso thank you for helping with this :pray: 

Quick update:
I've extracted the history, here is the wip: https://github.com/leogr/rules
I'll transfer it to the org soon :)

**Comment by leogr** [comment]
I think all points should be addressed now. So, I'm going to open a PR to update our config and make this repository "official". Then we can close this :partying_face:
