### ISSUE TITLE
Falco Graduation Path: Progress Tracker

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#281]
In alignment with the [suggestions from our TOC sponsors](https://github.com/cncf/toc/pull/956#issuecomment-1599367728), we're actively focusing on specific areas to improve The Falco Project, aiming to be fully prepared for the forthcoming Graduation Public Comment phase.

Comprehensive details of the proposed path are outlined in the following document :point_down: 

https://docs.google.com/document/d/12l65c6qC91akgFjzw7BM3KdNJAa5LyDG17sdpdfwf3g/edit?usp=sharing

This issue serves as a tracker for all related activities (see the task lists below).

## Get Feedback
```[tasklist]
- [x] Reach out to Taylor Dolezal
- [x] Understand how adopters use Falco
- [ ] https://github.com/falcosecurity/falco-website/issues/1036
- [ ] https://github.com/falcosecurity/falco-website/pull/1089
- [ ] https://github.com/falcosecurity/falco-website/pull/1070
```

## Tech Writing / Documentation
We will use [#falco-docs](https://cloud-native.slack.com/archives/C059LP08UJY) channel on the CNCF Slack to discuss those efforts.
```[tasklist]
- [x] File a service desk ticket with CNCF requesting a technical writer
- [ ] https://github.com/falcosecurity/falco-website/issues/1003
- [ ] https://github.com/falcosecurity/evolution/issues/271
- [ ] https://github.com/falcosecurity/falco-website/issues/1004
- [ ] https://github.com/falcosecurity/falco-website/issues/1006
- [ ] https://github.com/falcosecurity/falco-website/issues/1009
- [ ] https://github.com/falcosecurity/falco-website/issues/985
- [ ] https://github.com/falcosecurity/falco-website/issues/1031
- [ ] https://github.com/falcosecurity/falco-website/issues/1063
- [ ] https://github.com/falcosecurity/falco-website/issues/1007
- [ ] https://github.com/falcosecurity/falco-website/issues/1008
- [ ] https://github.com/falcosecurity/falco-website/issues/1005
- [ ] https://github.com/falcosecurity/falco/pull/2594
- [ ] https://github.com/falcosecurity/falco-website/pull/1069
- [ ] https://github.com/falcosecurity/falco-website/pull/1097
- [ ] https://github.com/falcosecurity/falco-website/pull/1085
- [ ] https://github.com/falcosecurity/falco-website/pull/1078
- [ ] https://github.com/falcosecurity/falco-website/pull/1077
- [ ] https://github.com/falcosecurity/falco-website/pull/1072
- [ ] https://github.com/falcosecurity/falco-website/pull/1090
- [ ] https://github.com/falcosecurity/falco-website/pull/1096
- [ ] https://github.com/falcosecurity/falco-website/pull/1099
- [ ] https://github.com/falcosecurity/falco-website/pull/1094
- [ ] https://github.com/falcosecurity/falco-website/pull/1106
- [ ] https://github.com/falcosecurity/falco-website/pull/1108
```

## Use Case Development
_Develop two primary use cases_
```[tasklist]
- [x] Detection use case published
- [x] Compliance use case published
- [ ] https://github.com/falcosecurity/falco-website/issues/1035
- [ ] https://github.com/falcosecurity/falco-website/pull/1027
- [ ] https://github.com/falcosecurity/falco-website/pull/1049
- [ ] https://github.com/falcosecurity/falco-website/pull/1054
```

## Kernel Version Testing
```[tasklist]
- [x] File a service desk ticket with CNCF requesting resources to perform kernel version testing
- [x] CNCF has provided resources to run tests in our CI
- [ ] https://github.com/cncf/cluster/issues/240
- [ ] https://github.com/falcosecurity/libs/issues/1191
- [ ] https://github.com/falcosecurity/libs/pull/1090
- [ ] https://github.com/falcosecurity/libs/pull/524
- [ ] https://github.com/falcosecurity/libs/pull/1131
```

## Rule Modularity/Assumptions
```[tasklist]
- [ ] https://github.com/falcosecurity/rules/issues/101
- [ ] https://github.com/falcosecurity/libs/pull/1095
- [ ] https://github.com/falcosecurity/rules/pull/76
- [ ] https://github.com/falcosecurity/rules/pull/115
- [ ] https://github.com/falcosecurity/rules/pull/102
- [ ] https://github.com/falcosecurity/rules/pull/103
- [ ] https://github.com/falcosecurity/rules/pull/106
- [ ] https://github.com/falcosecurity/rules/pull/108
- [ ] https://github.com/falcosecurity/rules/pull/109
- [ ] https://github.com/falcosecurity/rules/pull/110
- [ ] https://github.com/falcosecurity/rules/pull/112
- [ ] https://github.com/falcosecurity/rules/pull/113
- [ ] https://github.com/falcosecurity/rules/pull/114
- [ ] https://github.com/falcosecurity/rules/pull/122
- [ ] https://github.com/falcosecurity/rules/pull/125
```

**Comment by leogr** [comment]
# Status Update

I'm delighted to announce that we've completed all the action items recommended by our TOC sponsors (@TheFoxAtWork and @justincormack) and are on track with the proposed July and August timeline! Of course, this early completion doesn't imply a slowdown in our commitment to improving the project. Instead, it's renovated with the invaluable knowledge we've acquired from our experiences over the past few months.

As we reach this significant milestone, I've detailed a comprehensive, step-by-step status update below. I hope this information proves useful to you.

I've got to give a big shout-out to every person in the Falco community and the extended CNCF family who has been involved in this effort. Your contributions and support have made these initiatives fly. A special thank you goes to @nate-double-u for the help he's provided us.

cc @falcosecurity/core-maintainers 

## Get Feedback

Under the guidance of Taylor Dolezal, we've engaged multiple end-users to gather their feedback on Falco usage. We've established a robust process for receiving end-user feedback, including interviews with specific sets of questions aimed at understanding how Falco is used within their respective architectures. These interviews are converted into end-user case studies which we will continue to publish on https://falco.org/about/ecosystem/ as well as linking them from the falco.org home page. 

Activities completed include:
- [Trendyol case study](https://falco.org/about/case-studies/trendyol/): Highlighting how Trendyol uses Falco to develop a threat detection system by utilizing Kubernetes audit logs and kernel events to monitor user behavior in production clusters. This allows them to detect operational anti-patterns, improve visibility, and identify malicious actors.
- [R6 case study](https://falco.org/about/case-studies/r6-security/): Showcasing how R6 Security employs Falco to enhance their moving threat detection platform, Phoenix.


## Technical Writing / Documentation

In collaboration with Nate Waddington, we've worked on improving the Falco messaging and enhancing the quality of the Falco documentation, particularly focusing on new user onboarding. Based on his feedback and assessment, we've simplified and updated the Falco getting started guide and provided clear instructions on adopting Falco, including what additional projects users will need to make the most of Falco. Almost all of the website has been revised and improved. For full detail, see the related task list above.

Completed activities worth mentioning include:
 - Enhancing Falco messaging throughout falco.org and Falco GitHub repositories. 
- Enhancing clarity about each Falco component.
- Improving cross-references between all repositories, plugins, libraries, etc., leading to the main documentation site and the main repository, as well as the evolution repository. 
- Facilitating a better understanding of Falco content by adding a referenceable [glossary](https://falco.org/docs/reference/glossary/?all=true) on falco.org with frequently used terms. This includes references for individuals to learn more about eBPF, kernel security, syscalls, and more by adding links to third-party official documentation and websites.
- Massive reworking on [rules documentation](https://falco.org/docs/rules/) with clear instructions on styling and how to use, customize, and fine-tune rules according to various use cases (see the related section below for more detail).


## Use Case Development

We have increased clarity on Falco use cases and added two primary use cases on a dedicated falco.org/about/use-cases/ page. 

Completed activities include:
- Threat Detection use case: Added additional blogs and guides demonstrating how Falco can be used for threat detection. For example: 
    - [Defensive Capabilities for Container & Cloud Threats with Tidal](https://falco.org/blog/tidal-registry-release/)
- Compliance use case: Added additional blogs and guides showcasing how Falco can be used for Regulatory Compliance. Examples include:
    - [PCI/DSS Controls with Falco](https://falco.org/blog/falco-pci-controls/)
    - [Validating NIST Requirements with Falco](https://falco.org/blog/falco-nist-controls/)

## Kernel Version Testing

We've successfully implemented our [Driver Kernel Testing Framework](https://github.com/falcosecurity/libs/blob/master/proposals/20230530-driver-kernel-testing-framework.md) proposal. This effort includes the creation of a specific [falcosecurity/kernel-testing](https://github.com/falcosecurity/kernel-testing) sub-project featuring Ansible playbooks and Dockerfiles to manage FireCracker microVMs for testing drivers against a range of distros/kernel versions. We've also established CI jobs on the [falcosecurity/libs](https://github.com/falcosecurity/libs) repository to execute tests and generate a markdown table with the results on GitHub pages: https://falcosecurity.github.io/libs/matrix/. The CI is impressively speedy, completing runs in approximately 15 minutes. This accomplishment was made possible thanks to the [CNCF Community Infrastructure Lab (CIL)](https://github.com/CNCF/cluster), which we leverage to run our CI jobs for kernel testing.

Lastly, we're also considering further enhancements beyond the initial scope of this initiative. So, stay tuned!

## Rule Modularity/Assumptions

Building upon the [Falco Rules Adoption, Management, and Maturity Framework](https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md) proposal, we have made substantial progress in the adoption of Falco rules. We have successfully established a rule maturity framework and completed a comprehensive round of tagging and enhancing rules. This includes augmenting descriptions and providing tuning advice for stable rules. The newly introduced style guide has been applied to existing rules. 

To streamline the adoption process, we've put forth a thorough [style guide](https://falco.org/docs/rules/style-guide/) and an [adoption guide](https://falco.org/docs/rules/adoption-rules/) on our website. We have also included a dedicated [contributing guide](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md) within the rules repository to facilitate participation from contributors. To improve accessibility for adopters, we've introduced an overview document and improved cross-links to official documentation on our website. 

Looking ahead, we're working on additional enhancements that are currently in the pipeline, expected to be completed by the Falco 0.36 release.

**Comment by TheFoxAtWork** [comment]
Awesome this is great!  You all are on track for a Sept release? I want to verify the changes you've put in place with that release to confirm and wrap things up. CC @justincormack

**Comment by leogr** [comment]
Hey @TheFoxAtWork 

Thank you! :pray: 

Yes, we're on track for the Falco 0.36 release, due by September 29th. I can confirm that all the items mentioned will be included in this release. Currently, we're in the final stages of wrapping up various sub-components, such as the libs, rules, etc. This phase concludes around the end of August. From September, we'll transition into the "Release Preparation" iteration, focusing on thorough testing, addressing bugs, if any, and minor improvements. You can view a detailed breakdown on our [high-level roadmap](https://github.com/orgs/falcosecurity/projects/5/views/7).

**Comment by leogr** [comment]
Status update:
- We can close this tracking issue since the [vote passed](https://github.com/cncf/toc/pull/956#issuecomment-1763783382).
- We're now just waiting for CNCF GB & LC resolutions of a couple of license exception requests (see https://github.com/cncf/foundation/issues/629 and https://github.com/cncf/foundation/issues/645), then we can finally move to the graduation level :partying_face: 

/close
