### ISSUE TITLE
[Tracking] Review and Streamlining of 3rd-party Dependencies

### ISSUE THREAD

**Issue by leogr** [falcosecurity/evolution#308]
This issue is meant to track the ongoing effort of reviewing our 3rd-party dependencies. The objective of this continuous effort is to streamline our dependencies and ensure alignment with the [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).

```[tasklist]
### Related items
- [ ] https://github.com/falcosecurity/libs/pull/1316
- [ ] https://github.com/falcosecurity/evolution/issues/305
- [ ] https://github.com/cncf/foundation/issues/629
- [ ] https://github.com/falcosecurity/evolution/issues/330
```

**Comment by leogr** [comment]
We can assume this is done. 
/close

Further improvement will come with https://github.com/falcosecurity/evolution/issues/330
